brat:
  image: cassj/brat:1.3
  container_name: brat
  ports:
   - "8089:80"
  volumes:
   - "./brat-data:/var/www/brat/brat-v1.3_Crunchy_Frog/data"
  environment:
   - BRAT_USERNAME=brat
   - BRAT_PASSWORD=brat
   - BRAT_EMAIL=brat@example.com
